[project]
name = "osrs-coll-log-puller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gspread>=6.1.2",
    "oauth2client>=4.1.3",
    "requests>=2.32.3",
    "types-requests>=2.32.0.20240905",
]
